name: Build and deploy action

env:
  AZURE_WEBAPP_NAME: PROPERNEWTA2

on:
  push:
    branches:
      - "main"

permissions:
  contents: 'read'
  packages: 'write'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Login to container registry
        run: |
          docker login https://ghcr.io -u ${{ secrets.DOCKER_USERNAME}} -p ${{ secrets.DOCKER_KEY}}
      - name: Build and push image to registry
        run: |
          docker buildx build --push -t ${{ secrets.DOCKER_TAG }} .


  deploy:
    runs-on: ubuntu-latest

    needs: build

    steps:
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
          with:
            app-name: ${{ env.AZURE_WEBAPP_NAME }}
            publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
            images: 'ghcr.io/omvk97/testapp/fullapp'
